version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-tcs-rds"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-pngfqxvr2lvj"
s3_prefix = "sam-tcs-rds"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
